name: nexeye-ai-diagnostics
services:
  - name: web
    github:
      repo: YOUR_GITHUB_USERNAME/nexeye-ai-diagnostics
      branch: main
      deploy_on_push: true
    build_command: npm run build
    run_command: npm start
    environment_slug: node-js
    http_port: 8080
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /
    envs:
      - key: VITE_GEMINI_API_KEY
        value: ${VITE_GEMINI_API_KEY}
        type: SECRET
    health_check:
      http_path: /
      initial_delay_seconds: 20
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3
